// LOCALHOST
### 
GET http://localhost:3000/contacts

### 
GET http://localhost:3000/contacts/681397bc4fd361d08dfbb7a1 

### 
GET http://localhost:3000/contacts/681398294fd361d08dfbb7a2 

### 
GET http://localhost:3000/contacts/6813984c4fd361d08dfbb7a3


### Create/POST contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Mark",
    "lastName":"Jones",
    "email":"jones@email.com",
    "favoriteColor":"Orange",
    "birthday":"09/15/2001"
}

### PUT contact
PUT http://localhost:3000/contacts/68268f88423b889d6d6a2269 HTTP/1.1
content-type: application/json

{
    "firstName":"Mark",
    "lastName":"Jones",
    "email":"jones@email.com",
    "favoriteColor":"Blue",
    "birthday":"09/15/1998"
}

### DELETE Contact
DELETE http://localhost:3000/contacts/681cf4ea21bdcea3b430b66a HTTP/1.1



// Production Deploy
### Get all contacts
GET https://cse341-80ip.onrender.com/contacts

### Get contact by id
GET https://cse341-80ip.onrender.com/contacts/681398294fd361d08dfbb7a2 

### Create/POST Contact
POST https://cse341-80ip.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Mark",
    "lastName":"Jones",
    "email":"jones@email.com",
    "favoriteColor":"Orange",
    "birthday":"09/15/2001"
}

### PUT contact
PUT https://cse341-80ip.onrender.com/contacts/6826b302d1e6e54c5d9e4ab6 HTTP/1.1
content-type: application/json

{
    "firstName":"Mark",
    "lastName":"Jones",
    "email":"jones@email.com",
    "favoriteColor":"Blue",
    "birthday":"09/15/1998"
}

### DELETE Contact
DELETE https://cse341-80ip.onrender.com/contacts/6826b302d1e6e54c5d9e4ab6 HTTP/1.1